helsup/about/urls.py
from about import views
from django.urls import path

app_name = "about"

urlpatterns = [
    path("", views.about, name="about"),
]

helsup/helsup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path("", include("homepage.urls")),
    path("about/", include("about.urls")),
    path("users/", include("users.urls")),
    path("orders/", include("orders.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helsup/homepage/urls.py
from django.urls import path
from homepage import views

app_name = "homepage"

urlpatterns = [
    path("", views.home, name="home"),
]

helsup/orders/urls.py
from django.urls import path
from orders import views

app_name = "orders"

urlpatterns = [
    path("liked_orders", views.liked_orders, name="liked_orders"),
    path("my_orders", views.my_orders, name="my_orders"),
    path("show_orders", views.show_orders, name="show_orders"),
]

helsup/users/urls.py
from django.urls import path
from users.views import (ClientProfileView, ClientSignUpView,
                         VolunteerProfileView, VolunteerSignUpView, choice,
                         login_view, logout_view)

app_name = "users"

urlpatterns = [
    path("choice/", choice, name="choice"),

    path('volunteer/signup/', VolunteerSignUpView.as_view(), name='vol_signup'),
    path('client/signup/', ClientSignUpView.as_view(), name='cli_signup'),

    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),

    path("volunteer/profile", VolunteerProfileView.as_view(), name="vol_profile"),
    path("client/profile", ClientProfileView.as_view(), name="cli_profile"),
]

helsup/templates/includes/footer.html
<footer class="whitened">
    <div class="footer-columns">
        <div class="footer-column">
            <h3>© 2020 MayDa</h3>
        </div>
        <div class="footer-column">
            <h3>Contact us</h3>
            <ul>
                <li><a href="#">+7 747 521 95 08</a></li>
                <li><a href="#">dasiktazik@gmail.com</a></li>
                <li><a href="#">erke.toystore</a></li>
            </ul>
        </div>
        <div class="footer-column">
            <h3>Сделаем мир добрее</h3>
        </div>
    </div>
</footer>

helsup/templates/includes/index_header.html
{% load users_extras %}

<header id=""myHeader>
    <nav class="navbar">
            <div class="navbar__wrap">
            <div class="hamb">
                <div class="hamb__field" id="hamb">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
                </div>
            </div>
            <a href="/" class="logo" id="logo">InVol</a>
            <ul class="menu" id="menu">
                <li><a href="#">ПОДДЕРЖКА</a></li>
                <li><a href="#">ВОПРОСЫ</a></li>
                <li><a href="{% url 'about:about' %}">О НАС</a></li>

                <!-- ПРИ БЭКЕНДЕ ЕСЛИ УЖЕ ВОШЕЛ В АККАУНТ, ТО ВМЕСТО "ЗАКАЗАТЬ" БУДЕТ "ПРОФИЛЬ" -->
                {% if user.is_authenticated %}
                    <li><a href="{% url 'users:logout' %}">ВЫЙТИ</a></li>
                    {% if user|isinstance:"Volunteer" %}
                        <li><a href="{% url 'users:vol_profile' %}">ПРОФИЛЬ</a></li>
                    {% elif user|isinstance:"Client" %}
                        <li><a href="{% url 'users:cli_profile' %}">ПРОФИЛЬ</a></li>
                    {% endif %}
                {% else %}
                    <li><a href="{% url 'users:login' %}">ВОЙТИ</a></li>
                    <li><a href="{% url 'orders:my_orders' %}">ЗАКАЗАТЬ</a></li>
                {% endif %}
            </ul>
            </div>
        </div>
        </nav>
</header>

helsup/templates/includes/main_header.html
{% load static %}
{% load users_extras %}

<header class="header">
    <h1 class="header__logo"><a href="{% url 'homepage:home' %}">InVol</a></h1>
    <div class="header__nav">
        <div class="header__links">
            <a href="{% url 'orders:show_orders' %}" class="header__link header__link_selected">Заказы</a>
            <a href="{% url 'about:about' %}" class="header__link">О нас</a>
            <a href="#" class="header__link">Поддержка</a>
            <a href="#" class="header__link">Фильтр</a>
        </div>
        {% if user|isinstance:"Volunteer" %}
            {% if request.path == '/orders/show_orders' %}
                <a href="{% url 'orders:liked_orders' %}"><img src="{% static 'img/liked.png' %}" class="header__liked" alt=""></a>
            {% elif request.path == '/orders/my_orders' %}
                <a href="{% url 'orders:liked_orders' %}"><img src="{% static 'img/like_activated.png' %}" class="header__liked" alt=""></a>
            {% endif %}
            <a href="{% url 'users:vol_profile' %}"><img src="{% static 'img/user.svg' %}" class="header__user" alt=""></a>
        {% elif user|isinstance:"Client" %}
           <a href="{% url 'users:cli_profile' %}"><img src="{% static 'img/user.svg' %}" class="header__user" alt=""></a>
        {% endif %}
    </div>
</header>