helsup/about/urls.py
from about import views
from django.urls import path

app_name = "about"

urlpatterns = [
    path("", views.about, name="about"),
]

helsup/helsup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path("", include("homepage.urls")),
    path("about/", include("about.urls")),
    path("users/", include("users.urls")),
    path("orders/", include("orders.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helsup/users/urls.py
from django.urls import path
from users.views import (ClientProfileView, ClientSignUpView,
                         VolunteerProfileView, VolunteerSignUpView, choice,
                         login_view, logout_view)

app_name = "users"

urlpatterns = [
    path("choice/", choice, name="choice"),

    path('volunteer/signup/', VolunteerSignUpView.as_view(), name='vol_signup'),
    path('client/signup/', ClientSignUpView.as_view(), name='cli_signup'),

    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),

    path("volunteer/profile", VolunteerProfileView.as_view(), name="vol_profile"),
    path("client/profile", ClientProfileView.as_view(), name="cli_profile"),
]

helsup/users/models.py
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(
        max_length=255,
        verbose_name='имя'
    )
    email = models.EmailField(
        unique=True,
        verbose_name='электронная почта',
    )
    phone_number = models.CharField(
        max_length=20,
        verbose_name='телефонный номер'
    )

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'phone_number']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_staff

    def has_module_perms(self, app_label):
        return self.is_staff


class Volunteer(CustomUser):
    class Meta:
        verbose_name = 'Волонтер'
        verbose_name_plural = 'Волонтеры'
        permissions = (("accept_order", "Can accept order"),)


class Client(CustomUser):
    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        permissions = (("create_order", "Can create order"),)


class BaseProfile(models.Model):
    AGE_MIN = 14
    AGE_MAX = 128

    class Sex(models.TextChoices):
        MALE = 'M', 'Мужской'
        FEMALE = 'F', 'Женский'
        OTHER = 'O', 'Другое'

    age = models.PositiveIntegerField(
        validators=[MinValueValidator(AGE_MIN), MaxValueValidator(AGE_MAX)],
        null=True, blank=True,
        verbose_name='возраст',
    )
    sex = models.CharField(
        max_length=1,
        choices=Sex.choices,
        null=True, blank=True,
        verbose_name='пол',
    )
    city = models.CharField(
        max_length=255,
        null=True, blank=True,
        verbose_name='город'
    )
    about_me = models.TextField(
        null=True, blank=True,
        verbose_name='о себе'
    )
    rating = models.FloatField(null=True, blank=True)

    class Meta:
        abstract = True

    @property
    def city_display(self):
        return f"Адрес: {self.city}"


class VolunteerProfile(BaseProfile):
    volunteer = models.OneToOneField(Volunteer, on_delete=models.CASCADE, related_name='profile')


class ClientProfile(BaseProfile):
    class Mobility(models.TextChoices):
        NO = "Нету", "Люди, не имеющие ограничений по мобильности"
        M1 = "M1", "Люди, не имеющие инвалидности со сниженной мобильностью (люди пенсионного возраста, люди с детьми дошкольного возраста, беременные женщины), а также глухие и слабослышащие"
        M2 = "M2", "Пожилые немощные люди (в том числе инвалиды по старости), инвалиды с недостатками зрения, пользующиеся белой тростью"
        M3 = "M3", "Инвалиды и другие маломобильные граждане, не относящиеся к группе М2, использующие при движении дополнительные опоры (костыли, трости), инвалиды на протезах"
        M4 = "M4", "Инвалиды и другие маломобильные граждане, не относящиеся к группе М2, передвигающиеся на креслах-колясках"
        HM = "HM", "Немобильные граждане"
        HT = "HT", "Нетранспортабельные люди"
        HO = "HO", "Люди с ограниченной степенью свободы, в том числе люди с психическими отклонениями"

    client = models.OneToOneField(Client, on_delete=models.CASCADE, related_name='profile')
    mobility = models.CharField(
        max_length=4,
        choices=Mobility.choices,
        null=True, blank=True,
        verbose_name='мобильность'
    )

    @property
    def mobility_display(self):
        if self.mobility == 'Нету':
            return 'Нету мобильности'
        return f'Группа мобильности: {self.mobility}'


@receiver(post_save, sender=Volunteer)
def create_volunteer_profile(sender, instance, created, **kwargs):
    if created:
        VolunteerProfile.objects.create(volunteer=instance)


@receiver(post_save, sender=Client)
def create_client_profile(sender, instance, created, **kwargs):
    if created:
        ClientProfile.objects.create(client=instance)


@receiver(post_save, sender=Volunteer)
def save_volunteer_profile(sender, instance, **kwargs):
    instance.profile.save()


@receiver(post_save, sender=Client)
def save_client_profile(sender, instance, **kwargs):
    instance.profile.save()

helsup/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from users.models import (Client, ClientProfile, CustomUser, Volunteer,
                          VolunteerProfile)


class VolunteerSignUpForm(UserCreationForm):
    password1 = forms.CharField(
        label="Пароль",
        strip=False,
        widget=forms.PasswordInput(),
    )
    password2 = forms.CharField(
        label="Введите пароль еще раз",
        widget=forms.PasswordInput(),
        strip=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "input_box  "
            field.field.widget.attrs["required"] = "required"

        self.fields['first_name'].widget.input_type = 'text'
        self.fields['email'].widget.input_type = 'text'
        self.fields['phone_number'].widget.input_type = 'tel'

    class Meta(UserCreationForm.Meta):
        model = Volunteer
        fields = ("first_name", "email", "phone_number", "password1", "password2")
        labels = {
            "first_name": "Имя",
            "email": "Эл. почта",
            "phone_number": "Номер телефона",
        }


class ClientSignUpForm(UserCreationForm):
    password1 = forms.CharField(
        label="Пароль",
        strip=False,
        widget=forms.PasswordInput(),
    )
    password2 = forms.CharField(
        label="Введите пароль еще раз",
        widget=forms.PasswordInput(),
        strip=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "input_box  "
            field.field.widget.attrs["required"] = "required"

        self.fields['first_name'].widget.input_type = 'text'
        self.fields['email'].widget.input_type = 'text'
        self.fields['phone_number'].widget.input_type = 'tel'

    class Meta(UserCreationForm.Meta):
        model = Client
        fields = ("first_name", "email", "phone_number", "password1", "password2")
        labels = {
            "first_name": "Имя",
            "email": "Эл. почта",
            "phone_number": "Номер телефона",
        }


class UserLoginForm(forms.Form):
    email = forms.EmailField(label="Эл. почта")
    password = forms.CharField(widget=forms.PasswordInput, label="Пароль")

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "input_box"
            field.field.widget.attrs["required"] = "required"

        self.fields['email'].widget.input_type = 'text'
        self.fields['password'].widget.input_type = 'password'

    class Meta:
        fields = ("email", "password")


class UpdateCustomUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ("first_name", "email", "phone_number")


class UpdateVolunteerProfileForm(forms.ModelForm):
    class Meta:
        model = VolunteerProfile
        fields = ['age', 'sex', 'city', 'about_me']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False


class UpdateClientProfileForm(forms.ModelForm):
    mobility = forms.ChoiceField(choices=ClientProfile.Mobility.choices, required=False, label="Мобильность")

    class Meta:
        model = ClientProfile
        fields = ['age', 'sex', 'city', 'about_me', 'mobility']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False

helsup/users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as django_logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import CreateView
from users.decorators import client_required, volunteer_required
from users.forms import (ClientSignUpForm, UpdateClientProfileForm,
                         UpdateCustomUserForm, UpdateVolunteerProfileForm,
                         UserLoginForm, VolunteerSignUpForm)
from users.models import Client, Volunteer


# Sign Up Views
class VolunteerSignUpView(CreateView):
    form_class = VolunteerSignUpForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/signup.html'


class ClientSignUpView(CreateView):
    form_class = ClientSignUpForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/signup.html'


def choice(request):
    template_name = "users/choice.html"
    context = {}
    return render(request, template_name, context)


@login_required
def logout_view(request):
    django_logout(request)
    return redirect('homepage:home')


def login_view(request):
    template_name = "users/login.html"
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                if isinstance(user, Volunteer):
                    return redirect("orders:show_orders")
                elif isinstance(user, Client):
                    return redirect("orders:my_orders")
            else:
                form.add_error(None, 'Invalid email or password.')
    else:
        form = UserLoginForm()

    context = {
        'form': form
    }
    return render(request, template_name, context)


@method_decorator(login_required, name="dispatch")
class ProfileView(View):
    user_form_class = UpdateCustomUserForm
    profile_form_class = None
    template_name = "users/profile.html"
    redirect_url = None

    def get_user_profile(self, request):
        user = request.user
        profile = user.profile
        return user, profile

    def get(self, request):
        user, profile = self.get_user_profile(request)
        user_form = self.user_form_class(instance=user)
        profile_form = self.profile_form_class(instance=profile)
        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }
        return render(request, self.template_name, context)

    def post(self, request):
        user, profile = self.get_user_profile(request)
        user_form = self.user_form_class(request.POST, instance=user)
        profile_form = self.profile_form_class(request.POST, request.FILES, instance=profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect(self.redirect_url)
        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }
        return render(request, self.template_name, context)


@method_decorator(volunteer_required, name="dispatch")
class VolunteerProfileView(ProfileView):
    profile_form_class = UpdateVolunteerProfileForm
    redirect_url = 'orders:show_orders'


@method_decorator(client_required, name="dispatch")
class ClientProfileView(ProfileView):
    profile_form_class = UpdateClientProfileForm
    redirect_url = 'orders:my_orders'

helsup/templates/users/choice.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/choice.css' %}">
{% endblock css %}

{% block title %}
    <title>Document</title>
{% endblock title %}

{% block header %}
    <header>
        <a class="logo" href="/">InVol</a>
    </header>
{% endblock header %}

{% block content %}
    <img src="{% static 'img/freepik--character-1--inject-24.png' %}" alt="girl" class="first_girl">
    <img src="{% static 'img/freepik--character-4--inject-24.png' %}" alt="girl" class="second_girl">
    <div class="content">
        <div class="first_card card">
            <img src="{% static 'img/card_img.png' %}" alt="banner" class="banner elem">
            <div class="title elem">
                Волонтер
            </div>
            <div class="description elem">
                Оказывайте помощь тем, кто в ней нуждается, благодаря сайту InVol.
            </div>
            <a class="register elem" href="{% url 'users:vol_signup' %}">
                Стать волонтером
            </a>
        </div>
        <div class="second_card card">
            <img src="{% static 'img/card_img.png' %}" alt="banner" class="banner elem">
            <div class="title elem">
                Клиент
            </div>
            <div class="description elem">
                Закажите помощь для себя или для ваших близких, используя сайт InVol.
            </div>
            <a class="register elem" href="{% url 'users:cli_signup' %}">
                Для клиентов
            </a>
        </div>
    </div>
{% endblock content %}

helsup/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock css %}

{% block title %}
    <title>Вход</title>
{% endblock title %}

{% comment %} reset header {% endcomment %}
{% block header %}{% endblock header %}

{% block content %}
    <div class="content">
        <form class="container" method="POST">
            {% csrf_token %}
            <div class="row">
                <a class="title" href="/">InVol</a>
            </div>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        {{ error|escape }}
                    </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-primary">
                        {{ error|escape }}
                    </div>
                {% endfor %}
            {% endif %}
            {% for field in form %}
                <div class="row">
                    {{ field }}
                    <span>{{field.label_tag}}</span>
                </div>
            {% endfor %}
            <div class="row">
                <div class="row_buttons">
                    <button class="focused_btn" type="submit">Войти</button>
                    <a class="unfocused_btn" href="{% url 'users:choice' %}">Регистрация</a>
                </div>
            </div>
        </form>
    </div> 
{% endblock content %}

helsup/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock css %}

{% block title %}
    <title>Профиль</title>
{% endblock title %}

{% block content %}
    <main class="container">
        <div class="elem pfp">
            <img src="{% static 'img/pfp.png' %}" alt="" class="pfp__image">
            <div class="pfp__name">{{ user.first_name }}</div>
            <button class="profile__button" type="submit">Изменить</button>
        </div>
        <form class="elem properties" method="POST">
            {% csrf_token %}
            <div class="title">Информация о себе</div>
            {% for field in user_form %}
                <div class="row">
                    <span>{{ field.label }}</span>
                    <input type="text" name="{{ field.name }}" value="{{ field.value|default_if_none:"" }}">
                </div>
            {% endfor %}
            {% for field in profile_form %}
                <div class="row">
                    <span>{{ field.label }}</span>
                    <input type="text" name="{{ field.name }}" value="{{ field.value|default_if_none:"" }}" autocomplete="off">
                </div>
            {% endfor %}
            <button type="submit" class="profile__button">Сохранить</button>
        </form>
        <div class="elem decor">
            <img src="{% static 'img/freepik--Characters--inject-38.png' %}" alt="koten">
        </div>
    </main>
{% endblock content %}

<body>
    <main class="container">
        <div class="elem pfp">
            <img src="images/pfp.png" alt="" class="pfp__image">
            <div class="pfp__name">Марат Хусаинов</div>
            <button class="profile__button" type="submit">Изменить</button>
        </div>
        <div class="elem properties">
            <div class="title">Информация о себе</div>
            <div class="row">
                <span>Имя</span>
                <input type="text">
            </div>
            <div class="row">
                <span>Возраст</span>
                <input type="text">
            </div>
            <div class="row">
                <span>Пол</span>
                <input type="text">
            </div>
            <div class="row">
                <span>Эл. почта</span>
                <input type="text">
            </div>
            <div class="row">
                <span>Регион</span>
                <input type="text">
            </div>
            <div class="row">
                <span>Адрес</span>
                <input type="text">
            </div>
            <div class="row">
                <span>Инвалидность</span>
                <input type="text">
            </div>
            <div class="row">
                <span>О себе</span>
                <input type="text">
            </div>
            <button type="submit" class="profile__button">Сохранить</button>
        </div>
        <div class="elem decor">
            <img src="images/freepik--Characters--inject-38.png" alt="koten">
        </div>
    </main>
</body>
</html>

helsup/templates/users/signup.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock css %}

{% block title %}
    <title>Регистрация</title>
{% endblock title %}

{% comment %} reset header {% endcomment %}
{% block header %}{% endblock header %}

{% block content %}
    <div class="content">
        <form class="container" method="POST">
            {% csrf_token %}
            <div class="row">
                <a class="title" href="/">InVol</a>
            </div>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        {{ error|escape }}
                    </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-primary">
                        {{ error|escape }}
                    </div>
                {% endfor %}
            {% endif %}
            {% for field in form %}
                <div class="row">
                    {{ field }}
                    <span>{{field.label_tag}}</span>
                </div>
            {% endfor %}
            <div class="row">
                <div class="row_buttons">
                    <button type="submit" class="focused_btn">Далее</button>
                    <a class="unfocused_btn" href="{% url 'users:login' %}">Войти</a>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}